[package]
name = "boatest"
version = "0.1.0"
authors = ["elasmojs <66966290+elasmojs@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.8.0"
Boa = "0.9.0"
